apiVersion: apps/v1
kind: ReplicaSet
metadata: 
  name: frontend-rs
  labels:
    app: frontend
spec: # especificaçções do pod
  template:
    metadata:
      name: my-pod-web-server
      labels:
        apps: my-app
        tier: frontend
    spec: # especificações do container
      containers: 
        - name: my-container-nginx
          image: nginx
  selector: #seletor que vai controlar o pod, que neste caso é o my-app
    matchLabels:
      apps: my-app
  replicas: 4
 
