apiVersion: v1
kind: Service
metadata:
  name: svc-sts
spec:
  ports:
    - port: 80
  clusterIP: None # headless service
  selector:
    app: nginx-app-pods
---
apiVersion: apps/v1
kind: StatefulSet 
metadata:
  name: my-sts 
spec:
  selector:  
    matchLabels:
      app: nginx-app-pods
  serviceName: "svc-sts" # definição do serviço que vai fazer parte da configuração do statefulset, vai cuidar da identidade de redes dos pods
  replicas: 3
  template: # especificações dos pods
    metadata:
      labels:
        app: nginx-app-pods # label que o statefulset vai gerenciar
    spec:
      containers:
        - name: my-container
          image: nginx:1.23.1
          volumeMounts:
            - name: my-pv
              mountPath: /usr/share/nginx/html # volume que será montado dentro do container, padrão do nginx
  volumeClaimTemplates: # volume dinamico, especificações de cada um dos volumes
    - metadata:
        name: my-pv
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi # tamanho dos volumes