apiVersion: v1
kind: Service
metadata:
  name: jupyter-service
  namespace: jupyter
spec:
  selector:
    app: jupyter-app
  type: NodePort
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8888
      nodePort: 30090  # porta externa
