apiVersion: v1
kind: Pod 
metadata:
  name: web-pod
  labels:
    type: web-app
spec:
  containers:
    - name: web-server-apache
      image: httpd
      ports:
       - containerPort: 80 # por padrão a porta 80 já é usada, caso prefirir pode remover
    - name: web-server-tomacat
      image: tomcat
      ports:  
        - containerPort: 8080

 