apiVersion: v1
kind: Pod
metadata:
  name: pod-apache # 10.244.0.6 <---- (entrei dentro do pod e peguei este ip)
spec:
  containers:
  - name: my-apache-container
    image: httpd
---
apiVersion: v1
kind: Pod
metadata:
  name: pod-nginx # 10.244.0.7 <---- (entrei dentro do pod e peguei este ip)
spec:
  containers:
  - name: my-nginx-container
    image: nginx
   